=== songjian0270/kjuns_server/src/main/resources/dtd/validation.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT validators (validator)+>
<!ATTLIST validators
    xmlns CDATA #FIXED ''>

<!ELEMENT validator (field)+>
<!ATTLIST validator
    method NMTOKEN #REQUIRED
    target CDATA #REQUIRED>

<!ELEMENT field (rule)+>
<!ATTLIST field
	name NMTOKEN #REQUIRED
    dataType (String|Integer|Double|Long|List|Float) "String" >

<!ELEMENT rule EMPTY>
<!ATTLIST rule
    msg NMTOKEN #IMPLIED
    validate (notNull|notEmpty|emptyAble|fixedLen|minLen|maxLen|min|max|numeral|specified|email|regular|optional|emojiForbid) "notEmpty"
    value CDATA #IMPLIED>

=== songjian0270/kjuns_server/src/main/resources/validation/comment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "../dtd/validation.dtd">
<validators>

    <validator target="com.kjuns.controller.CommentController" method="queryComment">
	     <field name="id" dataType="String">
	 	    <rule validate="notEmpty" msg="动态ID不能为空"/>
	    </field>
	   	<field name="pageInvertedIndex" dataType="Integer">
	 		<rule validate="notEmpty" msg="反向结束索引不能为空"/>
	 		<rule validate="numeral" msg="反向结束索引应为数字"/>
	    </field>
	    <field name="pageSize" dataType="Integer">
	 		<rule validate="notEmpty" msg="显示条数不能为空"/>
	 		<rule validate="numeral" msg="显示条数应为数字"/>
	    </field>
    </validator>
    
    <validator target="com.kjuns.controller.CommentController" method="delComment">
	     <field name="id" dataType="String">
	 	    <rule validate="notEmpty" msg="评论ID不能为空"/>
	    </field>
	    <field name="contentId" dataType="String">
	 	    <rule validate="notEmpty" msg="内容ID不能为空"/>
	    </field>
	   	<field name="token" dataType="String">
	 	    <rule validate="notEmpty" msg="token不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
    
    <validator target="com.kjuns.controller.CommentController" method="add">
	     <field name="id" dataType="String">
	 	    <rule validate="notEmpty" msg="内容ID不能为空"/>
	        <rule validate="numeral" msg="内容ID应为数字"/>
	    </field>
	    <field name="content" dataType="String">
	 	    <rule validate="notEmpty" msg="内容不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>

</validators>

=== songjian0270/kjuns_server/src/main/resources/validation/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "../dtd/validation.dtd">
<validators>

	<validator target="com.kjuns.controller.UserLoginController" method="login">
		<field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
	</validator>
	
	<validator target="com.kjuns.controller.UserLoginController" method="cellPhoneNumberIsExisting">
		<field name="cellPhoneNumber" dataType="String">
	 	    <rule validate="notEmpty" msg="手机号不能为空"/>
	    </field>
	</validator>

	<validator target="com.kjuns.controller.UserLoginController" method="loginOut">
		<field name="token" dataType="String">
			<rule validate="notEmpty" msg="token不能为空" />
		</field>
		<field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
	</validator>
	
	<validator target="com.kjuns.controller.UserLoginController" method="complete">
		<field name="idcard" dataType="String">
			<rule validate="notEmpty" msg="身份证不能为空" />
		</field>
		<field name="realName" dataType="String">
			<rule validate="notEmpty" msg="真名不能为空" />
		</field>
		<field name="nickName" dataType="String">
			<rule validate="notEmpty" msg="昵称不能为空" />
		</field>
		<field name="id" dataType="String">
			<rule validate="notEmpty" msg="id不能为空" />
		</field>
		<field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
	</validator>

</validators>

=== songjian0270/kjuns_server/src/main/resources/validation/common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "../dtd/validation.dtd">
<validators>
    
    <validator target="com.kjuns.controller.CommonController" method="report">
	   	<field name="id" dataType="String">
	 		<rule validate="notEmpty" msg="举报内容ID不能为空"/>
	    </field>
	    <field name="type" dataType="Integer">
	 		<rule validate="notEmpty" msg="举报性质不能为空"/>
	    </field>
    </validator>
    
    <validator target="com.kjuns.controller.CommonController" method="insertFaq">
	   	<field name="title" dataType="String">
	 		<rule validate="notEmpty" msg="提问标题不能为空"/>
	    </field>
	      	<field name="content" dataType="String">
	 		<rule validate="notEmpty" msg="提问内容不能为空"/>
	    </field>
	   	<field name="token" dataType="String">
	 		<rule validate="notEmpty" msg="token不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
    
</validators>

=== songjian0270/kjuns_server/src/main/resources/validation/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "../dtd/validation.dtd">
<validators>

	<validator target="com.kjuns.controller.UserInfoController" method="getUserInfo">
		<field name="token" dataType="String">
			<rule validate="notEmpty" msg="token不能为空" />
		</field>
	</validator>

	<validator target="com.kjuns.controller.UserInfoController" method="getOtherUserInfo">
		<field name="userId" dataType="String">
			<rule validate="notEmpty" msg="用户ID不能为空" />
		</field>
	</validator>
	
<!-- 	<validator target="com.kjuns.controller.UserInfoController" method="completeUserInfo">
		<field name="faceSrc" dataType="String">
			<rule validate="notEmpty" msg="头像不能为空" />
		</field>
		<field name="sex" dataType="String">
			<rule validate="notEmpty" msg="性别不能为空" />
		</field>
		<field name="nickName" dataType="String">
			<rule validate="notEmpty" msg="昵称不能为空" />
		</field>
		<field name="token" dataType="String">
			<rule validate="notEmpty" msg="token不能为空" />
		</field>
		<field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
	</validator> -->
	
	<validator target="com.kjuns.controller.UserInfoController" method="nickNameIsExisting">
		<field name="nickName" dataType="String">
			<rule validate="notEmpty" msg="昵称不能为空" />
		</field>
		<field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
	</validator>
	
	<validator target="com.kjuns.controller.UserInfoController" method="changeUserInfo">
		<field name="token" dataType="String">
			<rule validate="notEmpty" msg="token不能为空" />
		</field>
		<field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
	</validator>

   
 
    
</validators>

=== songjian0270/kjuns_server/src/main/resources/validation/content.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "../dtd/validation.dtd">
<validators>

    <validator target="com.kjuns.controller.ContentController" method="list">
	     <field name="typeId" dataType="String">
	 	    <rule validate="notEmpty" msg="类别ID不能为空"/>
	    </field>
	   	<field name="pageInvertedIndex" dataType="Integer">
	 		<rule validate="notEmpty" msg="反向结束索引不能为空"/>
	 		<rule validate="numeral" msg="反向结束索引应为数字"/>
	    </field>
	    <field name="pageSize" dataType="Integer">
	 		<rule validate="notEmpty" msg="显示条数不能为空"/>
	 		<rule validate="numeral" msg="显示条数应为数字"/>
	    </field>
    </validator>
    
    <validator target="com.kjuns.controller.ContentController" method="detail">
	     <field name="id" dataType="String">
	 	    <rule validate="notEmpty" msg="评论ID不能为空"/>
	    </field>
    </validator>
    
    <validator target="com.kjuns.controller.ContentController" method="del">
	     <field name="id" dataType="String">
	 	    <rule validate="notEmpty" msg="评论ID不能为空"/>
	    </field>
	   	<field name="token" dataType="String">
	 	    <rule validate="notEmpty" msg="token不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
    
    <validator target="com.kjuns.controller.ContentController" method="add">
	     <field name="sectionId" dataType="String">
	 	    <rule validate="notEmpty" msg="栏目ID不能为空"/>
	    </field>
	     <field name="title" dataType="String">
	 	    <rule validate="notEmpty" msg="标题不能为空"/>
	    </field>
	    <field name="content" dataType="String">
	 	    <rule validate="notEmpty" msg="内容不能为空"/>
	    </field>
	    <field name="token" dataType="String">
	 	    <rule validate="notEmpty" msg="token不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
    
    <validator target="com.kjuns.controller.ContentController" method="like">
	     <field name="id" dataType="String">
	 	    <rule validate="notEmpty" msg="内容ID不能为空"/>
	    </field>
	   	<field name="token" dataType="String">
	 	    <rule validate="notEmpty" msg="token不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
  
    <validator target="com.kjuns.controller.ContentController" method="share">
	     <field name="id" dataType="String">
	 	    <rule validate="notEmpty" msg="内容ID不能为空"/>
	    </field>
	   	<field name="token" dataType="String">
	 	    <rule validate="notEmpty" msg="token不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>

</validators>

=== songjian0270/kjuns_server/src/main/resources/validation/sms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "../dtd/validation.dtd">
<validators>
    
    <validator target="com.kjuns.controller.SmsController" method="generateCheckCode">
	    <field name="cellPhoneNumber" dataType="String">
	 	    <rule validate="notEmpty" msg="手机号不能为空"/>
	    </field>
	    <field name="diallingCode" dataType="String">
	    	<rule validate="notEmpty" msg="国际码不能为空"/>	
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
    
    <validator target="com.kjuns.controller.SmsController" method="verifyCheckCode">
	    <field name="cellPhoneNumber" dataType="String">
	 	    <rule validate="notEmpty" msg="手机号不能为空"/>
	    </field>
	    <field name="checkCode" dataType="String">
	    	<rule validate="notEmpty" msg="验证码不能为空"/>	
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
    
</validators>

=== songjian0270/kjuns_server/src/main/resources/validation/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE validators SYSTEM "../dtd/validation.dtd">
<validators>
    
    <validator target="com.kjuns.controller.SystemController" method="requestUploadToken">
	    <field name="token" dataType="String">
	 	    <rule validate="notEmpty" msg="token不能为空"/>
	    </field>
	    <field name="signature" dataType="String">
			<rule validate="notEmpty" msg="signature不能为空" />
		</field>
    </validator>
    
    <validator target="com.kjuns.controller.SystemController" method="upgrade">
	    <field name="ver" dataType="String">
	 	    <rule validate="notEmpty" msg="版本不能为空"/>
	    </field>
	    <field name="platform" dataType="String">
			<rule validate="notEmpty" msg="平台不能为空" />
		</field>
    </validator>
    
</validators>
